### ISSUE TITLE
Scaling Kvdroid to A standalone Framework 

### ISSUE THREAD

**Issue by kengoon** [kvdroid/Kvdroid#18]
@yunus-ceyhan

You must have seen a whole lot of changes on my fork of your project, I want to scale it into something bigger. I renamed the fork due to your long absence from merging my previous PR(I saw your revert on my PR which shows you noticed). My Initial plan was not to pull away from Kvdroid, but due to your absence which made me think you might likely be abandoning Kvdroid, I decided to rename it on my own fork.

I want the `Kvdroid Community` to take the Kvdroid project to a framework level. I have noticed a few things while developing android software with Kivy, P4A and Buildozer; most of the time I tend to use more of Android Native code functionality more than Kivy's and also to enhance speed in some certain areas I use Android Native Widgets(Java) instead of Kivy widgets. This has made me to think of the possibility of scaling Kvdroid into a standalone framework which you can use in any Android project that is being compiled with P4A or Buildozer as just a package that will handle some Native code calls OR as As a direct GUI Application runner just like kivy, flutter, react native, etc... In the sense that it will be responsible for the UI of your Android Project. How is that possible you might ask? Just like every other event based application, we will make use of a while loop to retain the UI until an exit event occurs...... would discuss in details openly later(i.e if you bu the idea)

### The major changes that I made in the past months you were not around
- Created a `jclass` and `jimplement` packages. The `jclass` package will be responsible of reimplementing the Android API(Java precisely) into python and the separation of Android API classes (i.e Java Classes) into separate folder inside of the `jclass` package is the best practice for now due to  the fact that when autoclassing a Java class in `pyjnius` it wastes some time thereby causing freezing on low end devices(sometimes on higher devices if there are many autoclass to be done). The `jimplement` package is responsible for direct access to an already implemented Android Java functionality in Python(like notification and reading of contact)

PS: I would be waiting for your consent Also look into my fork to know more

**Comment by yunus-ceyhan** [comment]
Please check your email.
