### ISSUE TITLE
Create a separate python File for each function and class

### ISSUE THREAD

**Issue by kengoon** [kvdroid/Kvdroid#2]
Creating a separate  python file for each function and class will make the kivy app not to freeze due to too many pyjnius thread `on_ui_thread` processes and also it helps to avoid putting unnecessary permission not required by an app.

My kivy app crashes due to the `network_state` function. I understand pyjnius and that is how I figured out, that I need to request for `ACCESS_NETWORK_STATE` but for kivy noobs who don't understand will get frustrated. Please do consider this, or can I create a pull request because I'm already working on it

**Comment by yunus-ceyhan** [comment]
Sure, please create a pull requests. Thanks for your assistance.

**Comment by kengoon** [comment]
alright working on it

**Comment by yunus-ceyhan** [comment]
> alright working on it

I merged it but made some tiny changes on path file. could you please check.

**Comment by kengoon** [comment]
Ok

**Comment by kengoon** [comment]
Sure, I love how you placed both in one file because they both point to same context which is directories , you can close the issue now.
