### ISSUE TITLE
Network status not returning True if mobile data is active.

### ISSUE THREAD

**Issue by Azag3077** [kvdroid/Kvdroid#26]

**Comment by yunus-ceyhan** [comment]
I just checked it out and confirmed. I'll fix it asap. Thanks for feedback.

**Comment by Azag3077** [comment]
I already fixed it bro. I have created a Pull Request and merged it but I
can't see the changes I made on the main code.

I'm new to GitHub and this is first time creating a PR.

**Comment by Azag3077** [comment]
Am I supposed to merge the changes I made myself?

**Comment by yunus-ceyhan** [comment]
Ok i checked your solution and fixed it by it. Thanks for your contribution. 

https://github.com/kvdroid/Kvdroid/commit/cc9241f7f43fb3bc3d72ee8201dc1bb3627fe1fb

**Comment by Azag3077** [comment]
Alright, thanks.
I wanted to ask...Did I do the Pull Request the right way? I was hoping to
see my changes or link on the pull request tab but I didn't and I was
thinking no one too will.

**Comment by yunus-ceyhan** [comment]
After commiting changes on your fork just create a pull request then wait for the repo owner to merge it.

**Comment by Azag3077** [comment]
Thank you
