### ISSUE TITLE
Check data connection always return False

### ISSUE THREAD

**Issue by isaffathir** [kvdroid/Kvdroid#41]
im using

```python
from kvdroid.tools.network import network_status, wifi_status, mobile_status

print(network_status())  # for both wifi and mobile
print(wifi_status())    # only for wifi
print(mobile_status())    # only for mobile

```

but always return False any idea how to fix this?

![Screenshot_7](https://user-images.githubusercontent.com/88388332/206824329-96afc5f4-0818-4d3b-a818-60fedb5c9dbb.png)

**Comment by yunus-ceyhan** [comment]
Does your app have "ACCESS_NETWORK_STATE" permission?

**Comment by yunus-ceyhan** [comment]
"ACCESS_WIFI_STATE" permission can also be needed.
Check your `buildozer.spec` to confirm whether it has those permissions. If it still returns `False` let me know.

**Comment by isaffathir** [comment]
Cool thanks for the help

can you add this requirement to readme.md? let people know need to add this requirement in buildozer . so people would not confuse like me haha
