### ISSUE TITLE
How to add buffer on player.stream ?

### ISSUE THREAD

**Issue by isaffathir** [kvdroid/Kvdroid#42]
Im trying to make online music that stream music format .mp3 from url. but `player.stream()` doesnt play music if the music not fully downloaded its mean on low speed connection the music would not played

how to add buffer so user can stream music even on low speed connection?

**Comment by kengoon** [comment]
@isaffathir playyer.strem works seamlessly, you can verify by testing this https://github.com/kvdroid/KvDroidAssets/blob/main/demo_apk/kvdroid-0.1-armeabi-v7a_arm64-v8a-debug.apk. Documentation of the proper use case is on the way
