### ISSUE TITLE
error in Readme about dark_mode 

### ISSUE THREAD

**Issue by antorix** [kvdroid/Kvdroid#43]
In Readme:

> To check if device is in dark mode or not
> `from kvdroid.tools.darkmode import dark_mode`
> `print(dark_mode)`

It's an error in the last line. `dark_mode` is a function that returns True or False. Hence, it should be:

`print(dark_mode())`

**Comment by yunus-ceyhan** [comment]
Fixed. thanks for reporting.

**Comment by antorix** [comment]
and the same here: https://pypi.org/project/kvdroid/

**Comment by yunus-ceyhan** [comment]
> and the same here: https://pypi.org/project/kvdroid/

I'll fix it when I make a new pypi release. Thanks again.

**Comment by antorix** [comment]
> > and the same here: https://pypi.org/project/kvdroid/
> 
> I'll fix it when I make a new pypi release. Thanks again.

it's the same with `device_lang`. Maybe you can check other functions too
