### ISSUE TITLE
Notification arguments

### ISSUE THREAD

**Issue by KocWozniakPiotr** [kvdroid/Kvdroid#44]
Hello. I tried using the example of the `create_notification() `and changed `big_picture` and `large_icon` to my png icons but your example still doesn't work on android and actually crashed app when starting, also when its added to the the background service. 
Do I need some special formatting when adding path to the file?

There is no explanation how it really works and it would be really great to add some commenting or documentation for this feature.  
Are the arguments in your example mandatory and if so are those put in your example enough to test the notification feature? If not please give a proper explanation.

Until now I used `plyer` module for notifying but it's not perfect and has bugs when trying to use different icons.

Thank you for your hard work on the project! Best Regards!

**Comment by kengoon** [comment]
@KocWozniakPiotr apologies for taking this long to respond to your issues. The notification module is currently undergoing some updates. The example usage will be well documented this time around so that you will know the functionality of each parameters.
