### ISSUE TITLE
Read TEXT_AUTO_CAPS setting

### ISSUE THREAD

**Issue by antorix** [kvdroid/Kvdroid#45]
Maybe Kvdroid can implement the possibility to read one more Android setting from Kivy: TEXT_AUTO_CAPS (https://developer.android.com/reference/android/provider/Settings.System#TEXT_AUTO_CAPS). I need to get this setting in my app to control the text input, but have not yet found any way to do so.

**Comment by kengoon** [comment]
@antorix Kivy is responsible for handling the keyboard input behaviour, kvdroid cannot directly modify the behaviour of the keyboard, I think you could raise an issue in kivy repo. I will be closing this issue as it is not directly related to kvdroid
