### ISSUE TITLE
 AttributeError: 'android.content.pm.PackageInfo' object has no attribute 'getLongVersionCode'

### ISSUE THREAD

**Issue by Sahil-pixel** [kvdroid/Kvdroid#63]
Working fine in Android 13 but showing error in old android .

package_info() on  Android 8
i was testing in Android device SDK 26

AttributeError: 'android.content.pm.PackageInfo' object has no attribute 'getLongVersionCode'

**Comment by kengoon** [comment]
@Sahil-pixel the method was added in Android api version 28, so that's why it throws the error. I will go ahead and put an `if` guard to check for API 28

**Comment by Sahil-pixel** [comment]
Ok. Please update it
