### ISSUE TITLE
status bar not hiding 

### ISSUE THREAD

**Issue by Sahil-pixel** [kvdroid/Kvdroid#8]
immersive_mode(immerse=True) not hiding status bar in android 8
this is my VideoPy app in playstore i am updating .
see the image top portion status bar blocking kivy ui
![image](https://user-images.githubusercontent.com/57060638/120117643-c7c3d300-c1ab-11eb-80f1-0245faa5396b.png)

**Comment by yunus-ceyhan** [comment]
Unfortunatelly i dont have any device running Android 8. Also, immersive mode has dİfferent behaviors on different device.  If you find a solution please create a pull request.

**Comment by kengoon** [comment]
closing this issue. The author is requesting for full screen and not really immersive mode. New issue has #50 has been opened to address the fullscreen feature request

**Comment by yeyuchen198** [comment]
same problem, not working on My Android 10

**Comment by yeyuchen198** [comment]
maybe it is the kivy's BUG

**Comment by yeyuchen198** [comment]
yep, I found kivy only support set fullscreen or not before App run(), after that, the fullscreen can not be change

**Comment by yeyuchen198** [comment]
https://github.com/rpedroso/kivy_bug_7133/blob/fix/main.py

this is working
